typography_spectrum: 0.6694541773758829
color:
  saturation: 0.9921289731282741
  brandStrength: 0.3967040679417551
  rhythmicContrast: 0.2187235227320343
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.6490835647564381
layout_spectrum: 0.8501842590048909
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3c5727ac-83eb-4cb4-a304-c11a956d3185.jpg
name: The Headache Doctor
navigation:
  - name: Jason Sykes discussing headaches.
    id: ada7266f-e9b3-4c96-9a8b-096ecd078fbb
    type: content
  - name: The clinic waiting room.
    id: b8e07f00-d9aa-47b3-8a6e-b12ee92a8d4d
    type: content
  - name: 'Jason Sykes, Doctor of Chiropractic'
    id: c824c8f4-3637-40d5-a20d-d70784b4ba41
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Jason Sykes, Doctor of Chiropractic'
description: 'Finding and treating the cause of your headaches, without medications.'
